import type { Modes } from "../core/constants.ts";

/**
 * Encoder configuration options.
 */
interface Options {
  /**
   * Optional QR Code version to force.
   */
  version?: number;

  /**
   * Optional error correction level.
   */
  ec?: ErrorCorrectionLevel;

  /**
   * Optional mask pattern index.
   */
  mask?: number;
}

/**
 * A 16-bit packed numeric buffer used internally for bit stream operations.
 */
type Packs = Uint16Array;

/**
 * Describes the data capacity available for a specific QR Code version,
 * error correction level, and encoding mode.
 */
interface Capacity {
  /**
   * QR Code version number.
   */
  readonly version: number;

  /**
   * Error correction level encoded as an integer.
   */
  readonly ec: number;

  /**
   * Encoding mode for the segment.
   */
  readonly mode: Modes;

  /**
   * Maximum number of data bits or bytes available.
   */
  readonly capacity: number;
}

/**
 * Codeword block structure defining the raw data and error correction parameters.
 */
interface Codeword {
  /**
   * Number of data codewords in this block.
   */
  codewords: number;

  /**
   * Number of error correction codewords generated for this block.
   */
  ecCodewords: number;

  /**
   * Grouping of blocks and their respective data codewords.
   */
  groups: {
    /**
     * Number of blocks in this group.
     */
    blocks: number;

    /**
     * Number of data codewords per block.
     */
    dataCodewords: number;
  }[];
}

/**
 * Supported QR Code error correction levels.
 */
type ErrorCorrectionLevel = "L" | "M" | "Q" | "H";

/**
 * Codeword group array type.
 */
type Groups = Codeword["groups"];

/**
 * Raw byte block buffer used for interleaving and encoding operations.
 */
type Blocks = Uint8Array;

/**
 * Struct representing the fully compiled matrix payload generated by the QR Encoder.
 */
interface QRCode {
  /** The original string or numeric data payload supplied to the engine. */
  input: string | number;
  /** The length of the raw input sequence. */
  length: number;
  /** The selected encoding mode computed during data analysis. */
  mode: number;
  /** The final calculated QR Code version (ranging from 1 to 40). */
  version: number;
  /** The designated restoration error correction level capability. */
  ec: "L" | "M" | "Q" | "H" | string;
  /** The single-dimension module grid resolution (width/height block count). */
  modules: number;
  /** The mask pattern that yields the most reliable QR code (0–7). */
  mask: number;
  /** The final row-major flat binary matrix layout buffer (1 = active, 0 = empty). */
  matrix: Uint8Array;
}

/**
 * A flat square matrix buffer used to represent QR code modules.
 *
 * Each element represents a module state:
 * - `0` for light modules
 * - `1` for dark modules
 * - `255` for unset/reserved cells.
 */
type Matrix = Uint8Array;

export type {
  Blocks,
  Capacity,
  Codeword,
  ErrorCorrectionLevel,
  Groups,
  Matrix,
  Modes,
  Options,
  Packs,
  QRCode,
};
